CREATE TABLE "maintops"."incidents" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "maintops"."incidents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"reported_by_user_id" bigint NOT NULL,
	"handyman_user_id" bigint,
	"description" text NOT NULL,
	"incident_type" varchar(64),
	"urgency" varchar(32),
	"recommended_handyman_ids" bigint[],
	"agent_reasoning" text,
	"distance_km" numeric(10, 2),
	"travel_time_minutes" numeric(10, 2),
	"status" varchar(32) DEFAULT 'open' NOT NULL,
	"rating" integer,
	"feedback" text,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"assigned_at" timestamp,
	"completed_at" timestamp,
	"updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "chk_incident_rating" CHECK (((rating IS NULL) OR ((rating >= 1) AND (rating <= 5)))),
	CONSTRAINT "chk_incident_status" CHECK (((status)::text = ANY ((ARRAY['open'::character varying, 'recommended'::character varying, 'assigned'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying])::text[]))),
	CONSTRAINT "chk_incident_urgency" CHECK (((urgency IS NULL) OR ((urgency)::text = ANY ((ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying])::text[]))))
);
CREATE UNIQUE INDEX "incidents_pkey" ON "maintops"."incidents" ("id");
ALTER TABLE "maintops"."incidents" ADD CONSTRAINT "fk_incident_handyman" FOREIGN KEY ("handyman_user_id") REFERENCES "maintops"."users"("id");
ALTER TABLE "maintops"."incidents" ADD CONSTRAINT "fk_incident_reporter" FOREIGN KEY ("reported_by_user_id") REFERENCES "maintops"."users"("id");