CREATE TABLE "maintops"."users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "maintops"."users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" varchar(64) NOT NULL CONSTRAINT "users_email_key" UNIQUE,
	"password_hash" text NOT NULL,
	"first_name" varchar(64) NOT NULL,
	"last_name" varchar(64) NOT NULL,
	"date_of_birth" date,
	"phone" varchar(32),
	"house" varchar(128),
	"postal_code" varchar(32),
	"city" varchar(64),
	"state" varchar(64),
	"country" varchar(64),
	"latitude" double precision,
	"longitude" double precision,
	"is_handyman" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL
);
CREATE UNIQUE INDEX "users_email_key" ON "maintops"."users" ("email");
CREATE UNIQUE INDEX "users_pkey" ON "maintops"."users" ("id");